name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest    
    steps:
    - name: Install libudev-udev
      run: sudo apt-get install -y libudev-dev
    - uses: actions/checkout@v3
    
  build:
    runs-on: ubuntu-latest
    needs: setup 
    steps:
    - name: Build
      run: cargo build --verbose
      
  tests:
    runs-on: ubuntu-latest
    needs: build    
    steps:
    - name: Run tests    
      run: cargo test --verbose
